### ISSUE TITLE
bound() with sub bundles 

### ISSUE THREAD

**Issue by ramagottfried** [HfMT-ZM4/libo#9]
```
/foo = /bar
```
give us an you get an error that /bar is unbound, so then it makes sense that 

```
/foo = /bar./x
```
will also throw an error if /bar./x isn’t bound, you also get an error.

you can use bound() to check if an address is bound like:
```
/foo = bound(/bar)
```
which does not throw an error.

similarly, it would be good if you could check for sub-bundle addresses in the same way:

```
/foo = bound(/bar./x)
```

**Comment by ramagottfried** [comment]
related to libo issue #4 and https://github.com/HfMT-ZM4/CNMAT-odot/issues/4

**Comment by maccallum** [comment]
I believe this is fixed in commit b33643ade62ba268f03f85ada8245be922bcf2d0. Waiting for confirmation.

**Comment by ramagottfried** [comment]
great, yes the issue with bound() is fixed, thx

**Comment by ramagottfried** [comment]
oops, actually maybe not fixed:


<pre><code>
----------begin_max5_patcher----------
513.3ocqT00aaBCE8Y3WgkeJQxKfgjBcR6087duIJx.NstCrofIhtn7ee1Wa
ZIKQcaZSJwv8bO2Or84xov.bgZj2iQeF8.JH3TXP..YAB71A3F1XYMqGngUq
JUMspdNl37p4iZvSDyrdZqbqNpv7Fcq7LYqL5fc4kI10BIuTMHgP13AEUtTW
77mRlHdPI08hevsdnIqh8vpAcMWqesk6ZZLFsy6pkoKeRHebeGuT67ljr1DI
JIyl.DcSr8QV9p32BRNzHjlLBatjY09.qDJQ76Dc0FXR8n8ri7p8ECxpZ99Z
t7Q8SV2442xeESyb8U5FB59bSGQyrK1dKFVrXwThop+9eqWa9ah+9rKPt6Jh
oIj+OUjl3qX97JRi2bMyYum6BhFmLOpqy9DOZ5M3g1YOPOGFZWH+wZU9XamQ
vVwsDugf8KVAKBMWvZkrF7BiHsZQDaUTwRG5KFTVaa8qKP0rlhJ1hGF2Q7DG
s7VRPlbt7lZ8rq05z+Vs9WGpq+Fq76bMl7AVe3DAElHntGozz2r9WGIRmcAA
4B1++x2VfNxhe4sVuZnqbZW5OZPu2QU7dsPxzBkbFGymJPzKzEtxZtiNx658
jgRXjEOq5fISBXJjNSXNF2wOJl3mBHrNyAm1bpMzAsEd7t0XWnFwTmbP.QGZ
EilRBRNIqg225Oi.kY34veR7D1ii
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
bound doesn't return a value now

**Comment by ramagottfried** [comment]
and fixed! thanks @maccallum

**Comment by ramagottfried** [comment]
or almost fixed! : )

```
/foo = {
  /get/icon : 1
},
map(
    lambda([a],
        /test = a./get/icon,
        /test2 = bound(a./get/icon)
    ), getaddresses()
)
```

**Comment by maccallum** [comment]
This is fixed now

**Comment by maccallum** [comment]
can this be closed?

**Comment by ramagottfried** [comment]
ok just tested, looks good thanks
